<?xml version="1.0" encoding="utf-8"?><Database Name="BlogDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=BlogDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BlogDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Post" Member="Post">
    <Type Name="Post">
      <Column Name="PostID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostHeader" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PostText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PostTypeID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="PostType_Post" Member="PostType" ThisKey="PostTypeID" OtherKey="PostTypeID" Type="PostType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PostType" Member="PostType">
    <Type Name="PostType">
      <Column Name="PostTypeID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PostType_Post" Member="Post" ThisKey="PostTypeID" OtherKey="PostTypeID" Type="Post" />
    </Type>
  </Table>
</Database>